In [1]:
import torch

In [9]:
bs = 10
perm = torch.argsort(torch.rand(bs, 4), dim=1)
print(perm)
idx_for_gather = perm.unsqueeze(-1).expand(-1, -1, 7) 
print(mask)

tensor([[1, 0, 2, 3],
        [2, 1, 0, 3],
        [0, 2, 1, 3],
        [1, 0, 2, 3],
        [2, 1, 3, 0],
        [1, 2, 0, 3],
        [0, 1, 3, 2],
        [1, 0, 3, 2],
        [2, 0, 3, 1],
        [3, 0, 2, 1]])
tensor([3, 2, 4, 2, 3, 4, 4, 1, 3, 1])
tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])
tensor([[ True,  True,  True, False],
        [False,  True,  True, False],
        [ True,  True,  True,  True],
        [ True,  True, False, False],
        [ True,  True, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [False,  True, False, False],
        [ True,  True, False,  True],
        [False,  True, False, False]])
